### ISSUE TITLE
Use of COBRHA for healthcare provider (Organization) identification

### ISSUE THREAD

**Issue by ArdonToonstra** [hl7-be/core#23]
The [BeOrganization](https://build.fhir.org/ig/hl7-be/core/StructureDefinition-be-organization.html#root) does not mention  [CoBRHA](https://www.ehealth.fgov.be/ehealthplatform/nl/service-cobrha-common-base-registry-for-healthcare-actor). 

Wouldn't CoBRHA be suited for the identification of healthcare providers? Are there reasons this is not used in the BE core definition?

Or perhaps this relates to one of the defined identifier slices? (I am unsure what the CBE and the EHP identifier slice mean).

**Comment by bdc-ehealth** [comment]
The identifiers currently used allow identification in CoBRHA.
NIHII -> Number assigned by the NIHII (RIZIV/INAMI)
CBE -> Kruispuntbank ondernemingen (company registration)
EHP -> eHealthParty (organisation allowed to deal with eHealth Information)

**Comment by ArdonToonstra** [comment]
So for my understanding: the CoBRHA registry does not have its own identifiers for healthcare organizations?

**Comment by bdc-ehealth** [comment]
@ArdonToonstra : je kan COBRHA onderandere hier bekijken https://publiek.departementwvg.be/cobrha/. Het heeft wel een interne sleutel, maar de codes hierboven aangegeven zijn voldoende om een zorgverlener/instelling terug te vinden.

**Comment by bdc-ehealth** [comment]
WG: all information provided, we can close it. @fdetaver mentions that some organisations are difficult to identify. In Flanders they use an HCO number. Contact COBRHA for more information about this @bdc-ehealth .

**Comment by bdc-ehealth** [comment]
@fdetaver @HanneVuegen : I collected some more information on the HCO number, and the HCO number is not unique as such. It is only unique if it is accompanied by the "authentic source" of the number. So yes, Walloon and Brussels institutions can use an HCO number, if they have an "authentic source" for the number. Because the HCO number is only unique together with its "authentic source", it is not useful to create one NamingSystem on the Federal level. Flanders alone has several HCO numbers, each with their own "authentic source". This question is also linked to: https://github.com/hl7-be/core/issues/99#issuecomment-2069270298

**Comment by bdc-ehealth** [comment]
WG: for the use of the HCO number, each authentic source of the HCO-number will have to have its own NamingSystem, and the authentic source is responsible for keeping that NamingSystem (URL) stable. As such it can be used as an identifier.

**Comment by HanneVuegen** [comment]
Can we add Cobrha as a Namingsystem?

**Comment by bdc-ehealth** [comment]
@HanneVuegen ,

Could you make a screenshot of the COBRHA viewer, and indicate what would be the "NamingSystem" and what the "value"? I am not certain that I completely understand the question.

**Comment by HanneVuegen** [comment]
@bdc-ehealth,, sorry for the long wait:

When identifying Flemish HC institutions the NS could be representing the Authentic Source: 
OV_AGODI
WVG_VAZG
WVG_WS
WVG_JW
WVG_KG
WVG_VAPH

I don't know how this will look exactly, I guess it's best to match the token claim content to avoid mapping. So I will ask for some JSON examples to clarify. 

When the examples are there, can we take it to the core workgroups?

**Comment by HanneVuegen** [comment]
@bdc-ehealth 
So the authentic source is not available in the eHealths I.AM tokens. This makes it quiet complicated for software applications to know which AS to add as a NS. I see 2 possibilities:

- add the AS to the token (this was asked many times at eHealths but they are estimated not sufficient, maybe technical reasoning can help?)
- try to find a different NS that makes clear that it is only to be used in combination with CBE
- stay at the level of CBE and loose more detailed identification information of the organisation

What do you think? @ArdonToonstra @bdc-ehealth?

Kr,
Hanne

**Comment by ArdonToonstra** [comment]
Hi @HanneVuegen  -- I am currently not working for a Belgium project anymore. Also, I don't quite know the solution/answer to your questions. I hope @bdc-ehealth can help here :)

**Comment by HanneVuegen** [comment]
@ArdonToonstra ok, thanks for letting me know :-)

**Comment by HanneVuegen** [comment]
@bdc-ehealth, @costateixeira, we should re-open this issue since there is no clear conclusion.

eHealth advices against the use of URL based on eHealth.fgov.be. 

Since it is known that the HCO is always to be combined with CBE or authentic source. 
Since the authentic source is not available in the identity tokens for HCO organizations (I.AM/UMOE), but CBE is
Since the overlap in HCO for active 'Vlaamse Overheid' organisations is limited
and to avoid unneccesary complexity for implementers/endusers I propose the following URL for Flemish HealthCare Organizations:

https://www.vlaanderen.be/standards/fhir/Namingsystem/hco/VO
https://www.vlaanderen.be/standards/fhir/Namingsystem/site/VO 

FYI, all implementers should be able to add this organisation information whenever adding immunizations, allergys,... so we need this to be part of the eHealth IG NS/guidances. If no workgroups to discuss this issue are active, this request should be send by email to all involved.

For now we can work with project documentation but when can this be added to the different IG's? Or to NIHDI's the data glossary?
