### ISSUE TITLE
Do we need to get ready for R5?

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/core#40]
Some of our stakeholders express (implicitly) their wish to use R5 features (https://github.com/hl7-be/allergy/issues/86). Do we need to prepare for this?

**Comment by costateixeira** [comment]
The request is to have different codes and what we should do now about it.
And there is a defined option for now: we add extensions.

What new feature is there?

We should all prepare for the future releases, which is why we have agreed
to use logical data models. But I see no link between the interpretation of
the allergy issue and the need to consider R5.

Suggest starting the discussion with a broader scope.

**Comment by annabel-uzl** [comment]
https://github.com/hl7-be/core-clinical/issues/32 --> in this tread we discussed adding an extension to the procedure for SupportingInfo (an element that is already available in R5). 
What is the reasoning behind not switching to R5 instead of providing extensions? What are main reasons to decide to switch (or not to switch) to a new version?

**Comment by bdc-ehealth** [comment]
WG: we will evaluate and re-consider if and when to migrate and to which version when release R6 comes out
