### ISSUE TITLE
Structure of workgroups - some questions and concerns

### ISSUE THREAD

**Issue by annabel-uzl** [hl7-be/core#66]
I have some concerns regarding the workgroups that I would like to address in the hope to regain some structure during these meetings and to start the conversation about them. I'm quite new to the workgroups so I'm just trying to understand on where our focus needs to be at.

1. Are there some basic rules regarding deviating from the international standard? I was under the impression that we would try the follow the international standard as much as possible and thus try to avoid adding extensions to resources as much as possible? Is this assumption correct?
2. It is my believe that during the working groups we try to obtain a belgium profile for the fhir resources. Therefore, it seems not that productive to start extensive technical conversations about stuff like identifiers. This does not mean that one cannot have these discussions as we need to be on the same line and it needs to be understandable for everyone, but I do think that certain technical discussions need to be limited to a certain time range and can then be better hold in the chat such that the more technical people can explain the concept of an identifier while the meeting can continue, or that those questions are asked after the meeting here on github or by contacting a certain person. By limiting certain conversations to a certain time frame, we have more time for other discussions. But I'd like to hear some opinions on this matter.
3. I'm curious on why we're switching from resource to resource. Three weeks ago, we started with Problem but we didn't get far due to the identifier thing, last week we did Condition. I heard whispers in the hallway that this was due to some stakeholders asking for this. Where can we give those requests? And who decides what's more urgent? If we're continuing with Problem in a couple weeks, are we going to start again with identifier?
4. This might be already discussed, but since I'm new I'm just going to ask: is there a way for stakeholders to address how they would use certain fhir resources before the workgroup starts? Then we could already have a full view on soms believes and maybe some fields can already be skipped (e.g. everyone agrees that the identifier is 1 to many and stays named identifier).

I have the feeling, but that might be a me-thing, that the workgroups are at this point not as usefull as they can be (and by that I absolutely do not want to disrespect the hard work done by everyone, I'm just trying to address some stuff but further am a young newbie who knows nothing). There is still a lot of work that needs to be done. I'm hoping that, by starting this thread, we can address some things and make the workgroups more productive :)

**Comment by bdc-ehealth** [comment]
@annabel-uzl ,

Hi Annabel,

I fully agree that the workshops are not as productive as they could be. The workshops can be made more productive by asking detailed questions in separate github issues. Github issues that contain too much content ( such as an entire document by RIZIV/INAMI ) are too large to be discussed. That is why we asked from the beginning to create a separate github issue for every question you have. We can handle these questions one by one, and easily switch priorities upon simple request from a participant to the meetings. I don't know whether Michel Feron forwarded you this link: https://docs.google.com/presentation/d/1awfAFUtveTiNbJXyHptX2_ZUpakFli-qT6fbiFq_D-s/edit#slide=id.p .  This contains all information for optimal productivity. 

SUMMARY:

You as a member of the Workgroup should split up all your questions in separate manageable github issues. One question with one answer per issue. If you think the question does not have enough priority, clearly speak up during the meeting.

**Comment by annabel-uzl** [comment]
Hi @bdc-ehealth thanks for the link to the presentation. I didn't see it yet so it's usefull. And thanks for the tip to seperate questions in different issues :)

**Comment by costateixeira** [comment]
Hello Annabel

Thanks.

1. There are some rules for profiling: Our process considers the data that
we really need functionally, inspired but independently of whether they
exist in FHIR R4, or international extensions, or core extensions, or we
need a Belgian extension. There is NO rule that we should avoid extensions
per se - but if we see lots of extensions, this is a symptom that something
was missing in FHIR or in our analysis. Keep in mind that we are using FHIR
R4 and meanwhile FHIR has evolved and is evolving, so we could never say
"we want to avoid extensions" as the end of a discussion. The meetings
start with capturing the agreed data needs, before linking to FHIR. I don't
think there's agreement that .identifier is 1..* .

2. I'd like to confirm that we are not handling the internal system
architecture, but the common expectations for data exchange. The question
of identifiers appears in 2 separate discussions, so it should be handled
separately and transversally. But it is an expectable challenge from a
profiling perspective: Functionally, is .identifier 0..*. 0..1, 1..1? Is a
unique business identifier mandatory? Do we want to reject
other identifiers? That is what we need to see. That - and types of
identifiers that we may want to support - is our data exchange challenge.
Sometimes, the discussion goes into "what is the content of an identifier",
or "should hospitals have their own identifier", or "who is going to
reconcile the identifiers". Those are questions that we can use for
scoping, just to see if our decision is solid, but should not be the focus
of the discussion. For example, if we decide that the national identifier
is mandatory (because the vaults explicitly require it), this may mean that
in all cases where a national identifier is not (yet) available, we cannot
use the BE profile. Or the decision of whether to reject messages if they
contain several identifiers - there is no need for the interfaces to force
that. In addition, if we force that, we actually prevent any future
cross-referencing of identifiers. The care of Patient identifier is a good
example: In most cases we have the NISS number. But for newborns, refugees,
tourists etc. we don't. And for privacy reasons we may want to avoid it
being mandatory. So it cannot be optional (otherwise we cannot identify
tourists as subject of care) and should not be only 1 (otherwise we cannot
link the John Doe with their passport ID with the national number that will
only be found tomorrow). There's a wikipedia page, but more importantly, I
think, there's some guidance implicit and explicit in the FHIR
specification - most resources have a 0..* identifier.  There are several
architectures to deal with the identifiers, several technologies, etc. but
at the end, there is a perspective that the same resource may live in
different systems, and needs to be identified throughout its lifecycle. I
think a separate discussion would make more sense indeed, but we only
realized it this way. Thanks for confirming. There will be apparently
conflicting requirements, but what we want is to resolve them and come up
with a common answer. For example .identifier 0..* is good for everyone.
1..* may exclude some use cases. So we need to stay in the agreement zone.
We sometimes use a rule: Be strict with the data you send, be tolerant with
the data you receive. That is built into FHIR and in our way of working,.

3. The agenda was issued a bit before, because there was a need to expose
the Observation resource (while we were addressing the Problem initially,
indeed). Any stakeholder can request agenda changes, depending on the level
of readiness and expectations. I encourage anyone to intervene in the
agenda setting. There should be more continuity but sometimes it happens
that we need to look at something to comment early. If there's no feedback,
there's a risk of silo design and deciding that Identifiers are 1..1 - and
then technically it's much more difficult to make things work.

4. I don't understand the "address how they would use certain FHIR
resources before the workgroup starts". If we start the discussion on a
functional need, we don't all need to dive into the technical stuff. Some
meetings are very productive, others are not. It is very important to have
feedback and at every step, helping the discussion not diverge (or not
start with technical preferences and assumptions). Progressively walk
through things we can agree upon, instead of letting things be very
divergent and only at the end realize we have different perspectives.
Therefore, again my recommendation: The meetings at the logical data model
level are not  technical and we should not use only FHIR before
understanding what we need. There are plenty examples where the discussion
went directly to the technical implementation - costing a lot of
uncertainty and debates.

In Belgium there is a buildup of recommended functional data sets
(CareSets) which are implemented in FHIR. That makes things easier
especially for multipurpose resources. For example CarePlan can be used for
different purposes. Same with MedicationRequest, and ServiceRequest. What
matters is that there's a growing catalog of "what do i want to exchange
and how that works in FHIR", which is better IMO than "what can i do with
FHIR".

Sorry for the long reply. I think we can do 2 things:
1. At the beginning of the meeting, set the house rules.
2. Split the Identifier discussion to a transversal concept.

**Comment by costateixeira** [comment]
(PS: I do think that Identifier will end up being 1..* but if we start
discussing a specific identifier, that I don't think is mandatory.)

**Comment by annabel-uzl** [comment]
Hi @costateixeira thanks for the extended reply, that really clears some things up for me (I also edited my message a bit after sending it but I don't think you caught that on email).

1. About the extension: I didn't thought about the switching of versions, that's a very good point. I also didn't want to imply to forbid extensions or say we cannot use them, but I thought the goal was to stay in line with the international standard. As I understand now, it's better to start from a functional point of view and to see what we want and need and then after that compare it with the international standard? 

2. About the identifier: thanks for the example of the Patient, didn't thought about that. 

3. How can we intervene in the agenda setting? is this also a thread on Github?

4. My question wasn't very clear. I meant more like: is there a way to share our preferences on a certain resource before the workgroup meetings? Or is that not the purpose? E.g. for Problem we would like to see this and this field with this cardinality. In the ppt that Bart sent, I saw this might be possible using branches? Is that the way to do it when wanting to share opinions about references?

Since I'm quite new, I've only done two workgroups so my concerns were only based on those two ;)

**Comment by bdc-ehealth** [comment]
@annabel-uzl 
WG:
on question 1: We follow the international standard in that way that we RESTRICT it to the Belgian situation, and we add extensions if we cannot find an element that provides for the Belgian need.
on question 2: We are not in favour of imposing a time limit, we think that signalling priority at the start of the meeting is sufficient not to be starved.
on question 3: You are always able to signal priority at the start of the meeting. So you can determine the topic yourself.
on question 4: Normally documentation is available as an issue beforehand, as a result of the business expert workgroup. Other comments and different use cases can always be added as comments to the issue.
